openapi: 3.0.0
info:
  version: 2.0.0
  title: Mars
  license:
    name: just give me some beer :)
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /plateaus:
    get:
      summary: List all plateaus
      operationId: listPlateaus
      tags:
        - plateaus
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of plateaus
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Plateaus"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /plateaus/{plateauId}/commands/create:
    post:
      summary: Create a plateau
      operationId: createPlateaus
      tags:
        - plateaus
      parameters:
        - name: plateauId
          in: path
          required: true
          description: The id of the plateau to retrieve
          schema:
            type: string
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/PlateauCreateCommand"
      responses:
        303:
          description: Null response, see Location header
          headers:
            Location:
              schema:
                type: string
              description: Url to get the resulting plateau read model.
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


  /plateaus/{plateauId}:
    get:
      summary: Info for a specific plateau
      operationId: showPlateauById
      security:
        - api_key: []
      tags:
        - plateaus
      parameters:
        - name: plateauId
          in: path
          required: true
          description: The id of the plateau to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Plateaus"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    PlateauCreateCommand:
      type: object
      properties:
        x:
          type: integer
          format: int64
        y:
          type: integer
          format: int64
    Plateau:
      type: object
      required:
        - id
        - x
        - y
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Plateaus:
      type: array
      items:
        $ref: "#/components/schemas/Plateau"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
      openIdConnectUrl: "http://www.example.com" # I don't know why but this parameter is required even if type is basic or apiKey. I think It's OAS bug
